package by.eriomkin.euler.first;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem02 {

	public static void main(String[] args) {
		
		int fib1;
		int fib2;
		int result;
		int temp;
		
		fib1 = 1;
		fib2 = 2;
		result = 0;
		
		while (fib2 < 4_000_000) {
			if ((fib2 % 2) == 0) {
			result += fib2;
			}
			temp = fib2;
			fib2 = fib1 + fib2;
			fib1 = temp;
		}
		
		System.out.println(result);

	}

}
